### ISSUE TITLE
Website doesn't look like the demo one

### ISSUE THREAD

**Issue by dersuchendee** [CollectionBuilder/collectionbuilder-gh#65] opened 2022-12-22 17:07 UTC
I tried to follow the steps and it worked, but it seems the website doesn't look like the demo one. Is some asset missing? The style seems off/different, some buttons are over the place, and I have just modified the content a little (e.g. images, metadata, description).

My website: https://dersuchendee.github.io/trovalarana-liceogalvani/

**Comment by evanwill** [comment] 2022-12-22 17:23
@dersuchendee in [a commit you removed the yaml front matter](https://github.com/dersuchendee/trovalarana-liceogalvani/commit/c9a2fe43251f1ff91f7e682118e843cd9b7c3b40) from custom.scss. That means that Jekyll won't process the file, thus it doesn't exist on your final website--so you don't have the custom CSS file to provide the styles. 

Did you delete the yaml header to fix some other error you were getting?

**Comment by dersuchendee** [comment] 2022-12-22 17:29
Yeah I had a build error when building the bundle, I looked up on google and it seemed like there was some incompatibility... is there any way to keep it without having issues?

**Comment by evanwill** [comment] 2022-12-24 06:23
@dersuchendee you were impacted by the [bug described in this discussion](https://github.com/CollectionBuilder/collectionbuilder.github.io/discussions/73). If you want the build to work on your local machine, try renaming the "custom.scss" as described in the discussion post. The issue is fixed in the CB templates now!

**Closed by evanwill** 2022-12-24 06:23 UTC
